### ISSUE TITLE
Video creation time

### ISSUE THREAD

**Issue by naserpiltan** [gopro/gpmf-parser#134]
Hello David and thank you for this great work.
I would like to get my video creation time and have found this piece of code in **GPMF_mp4reader.c** file :

```
 md.creation_time =  BYTESWAP32(md.creation_time);
 md.modification_time = BYTESWAP32(md.modification_time);
 md.time_scale = BYTESWAP32(md.time_scale);
 md.duration = BYTESWAP32(md.duration);
```
I print the **md.creation_time** on my console and it gives me a huge number like this : **3671513887**.
But I don't know what this number actually is and how can convert it to a human readable format.
Could you plz give some hints about this parameter and converting it to a readable format ?

**Comment by dnewman-gpsw** [comment]
From this Apple Spec: https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html

Creation time
A 32-bit integer that specifies the calendar date and time (in seconds since midnight, **January 1, 1904**) when the movie atom was created. It is strongly recommended that this value should be specified using coordinated universal time (UTC).
